In [1]:
import pandas as pd
import numpy as np
import glob

In [3]:
eaf_csvs = glob.glob("../data/eaf/sets/*.csv")
eaf_dfs = [pd.read_csv(f, index_col=0) for f in eaf_csvs]
eaf_data = pd.concat(eaf_dfs, ignore_index=True)
eaf_data

,batch_id,MX_C_lSc,MX_SiO2_lSl,MX_FeO_lSl,T_lSl,T_lSc,C_inj,DRI_add,FM_inj,O2_lance,O2_post,P_arc,C_inj_sensitivity,DRI_add_sensitivity,FM_inj_sensitivity,O2_lance_sensitivity,O2_post_sensitivity,P_arc_sensitivity,time
0,5,0.003483,0.382094,0.031275,1943.0156,2005.1372,0.24,90.0,1.2,3.00,0.8,35500.0,0.000172,0.000010,0.000095,-0.000391,0.000103,7.583947e-09,599.9
1,5,0.004327,0.405575,0.004783,1867.1572,1939.5558,0.24,90.0,1.2,3.00,0.8,35500.0,0.003109,0.000024,0.000138,-0.001112,0.000565,1.003658e-08,1199.8
2,5,0.005514,0.408553,0.003247,1840.8481,1916.6050,0.24,90.0,1.2,3.00,0.8,35500.0,0.005098,0.000034,0.000129,-0.002008,0.001546,1.161145e-08,1799.7
3,5,0.006364,0.409407,0.002978,1830.3356,1906.8014,0.24,90.0,1.2,3.00,0.8,35500.0,0.005761,0.000035,0.000126,-0.002747,0.003016,1.199034e-08,2399.6
4,13,0.003495,0.381978,0.031236,1960.9545,2023.9833,0.24,90.0,1.2,3.00,1.0,42500.0,0.000173,0.000012,0.000098,-0.000397,0.000109,6.843362e-09,599.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12003,1604,0.003090,0.397553,0.030773,2057.6228,2137.4612,0.24,100.0,1.5,5.75,0.7,45000.0,0.000886,0.000025,0.000057,-0.000414,0.000237,2.144607e-09,2399.6
12004,1612,0.002885,0.348294,0.119181,2045.8833,2118.7200,0.24,100.0,1.5,5.75,1.0,40000.0,-0.000091,0.000009,0.000071,-0.000217,0.000097,5.063213e-09,599.9
12005,1612,0.002945,0.380441,0.057269,2050.0347,2127.6516,0.24,100.0,1.5,5.75,1.0,40000.0,0.000047,0.000017,0.000041,-0.000239,0.000218,3.643588e-09,1199.8
12006,1612,0.003073,0.392705,0.036893,2060.0605,2140.3640,0.24,100.0,1.5,5.75,1.0,40000.0,0.000523,0.000021,0.000060,-0.000357,0.000326,2.915360e-09,1799.7
12007,1612,0.003154,0.396504,0.032152,2075.0020,2156.1440,0.24,100.0,1.5,5.75,1.0,40000.0,0.000753,0.000023,0.000073,-0.000430,0.000401,2.250599e-09,2399.6

In [4]:
eaf_data.columns

Index(['batch_id', 'MX_C_lSc', 'MX_SiO2_lSl', 'MX_FeO_lSl', 'T_lSl', 'T_lSc',
       'C_inj', 'DRI_add', 'FM_inj', 'O2_lance', 'O2_post', 'P_arc',
       'C_inj_sensitivity', 'DRI_add_sensitivity', 'FM_inj_sensitivity',
       'O2_lance_sensitivity', 'O2_post_sensitivity', 'P_arc_sensitivity',
       'time'],
      dtype='object')

In [16]:
input_cols = ["C_inj", "DRI_add", "FM_inj", "O2_lance", "O2_post", "P_arc"]
time_input_cols = ["time"] + input_cols
output_cols = ["MX_C_lSc", "MX_SiO2_lSl", "MX_FeO_lSl", "T_lSl", "T_lSc"]
eaf_cleaned = eaf_data[time_input_cols + output_cols].dropna()
eaf_cleaned

,time,C_inj,DRI_add,FM_inj,O2_lance,O2_post,P_arc,MX_C_lSc,MX_SiO2_lSl,MX_FeO_lSl,T_lSl,T_lSc
0,599.9,0.24,90.0,1.2,3.00,0.8,35500.0,0.003483,0.382094,0.031275,1943.0156,2005.1372
1,1199.8,0.24,90.0,1.2,3.00,0.8,35500.0,0.004327,0.405575,0.004783,1867.1572,1939.5558
2,1799.7,0.24,90.0,1.2,3.00,0.8,35500.0,0.005514,0.408553,0.003247,1840.8481,1916.6050
3,2399.6,0.24,90.0,1.2,3.00,0.8,35500.0,0.006364,0.409407,0.002978,1830.3356,1906.8014
4,599.9,0.24,90.0,1.2,3.00,1.0,42500.0,0.003495,0.381978,0.031236,1960.9545,2023.9833
...,...,...,...,...,...,...,...,...,...,...,...,...
12003,2399.6,0.24,100.0,1.5,5.75,0.7,45000.0,0.003090,0.397553,0.030773,2057.6228,2137.4612
12004,599.9,0.24,100.0,1.5,5.75,1.0,40000.0,0.002885,0.348294,0.119181,2045.8833,2118.7200
12005,1199.8,0.24,100.0,1.5,5.75,1.0,40000.0,0.002945,0.380441,0.057269,2050.0347,2127.6516
12006,1799.7,0.24,100.0,1.5,5.75,1.0,40000.0,0.003073,0.392705,0.036893,2060.0605,2140.3640
12007,2399.6,0.24,100.0,1.5,5.75,1.0,40000.0,0.003154,0.396504,0.032152,2075.0020,2156.1440

In [22]:
len(input_cols), len(output_cols)

(6, 5)

In [ ]:
eaf_cleaned.to_csv("../data/eaf/eaf_cleaned.csv", index=False)
eaf_cleaned.describe()

,time,C_inj,DRI_add,FM_inj,O2_lance,O2_post,P_arc,MX_C_lSc,MX_SiO2_lSl,MX_FeO_lSl,T_lSl,T_lSc
count,10830.000000,10830.000000,10830.000000,10830.000000,10830.000000,10830.000000,10830.000000,10830.000000,10830.000000,10830.000000,10830.000000,10830.000000
mean,1436.270277,0.232454,94.464081,1.417932,4.433703,0.959663,41376.500462,0.003957,0.384715,0.041763,1986.911281,2060.923253
std,662.883328,0.015650,4.670860,0.314966,1.430038,0.265778,8119.658544,0.002130,0.025740,0.046139,111.650189,112.283331
min,599.900000,0.200000,90.000000,0.750000,1.500000,0.500000,30000.000000,0.000760,0.077324,0.000440,1389.267000,1007.585750
25%,599.900000,0.240000,90.000000,1.200000,3.500000,0.750000,37500.000000,0.002902,0.372956,0.006895,1925.479150,2000.734900
50%,1199.800000,0.240000,96.000000,1.400000,4.000000,1.000000,40000.000000,0.003475,0.389291,0.028536,1985.462150,2057.115800
75%,1799.700000,0.240000,96.000000,1.600000,5.750000,1.100000,42500.000000,0.004517,0.402826,0.059438,2053.245350,2127.006850
max,2399.600000,0.240000,110.000000,2.500000,8.000000,2.000000,75000.000000,0.093173,0.443702,0.201637,3191.810000,3139.690700

In [19]:
for col in time_input_cols:
    print(f"Unique values in {col}: {eaf_cleaned[col].nunique()}")

Unique values in time: 4
Unique values in C_inj: 2
Unique values in DRI_add: 4
Unique values in FM_inj: 9
Unique values in O2_lance: 9
Unique values in O2_post: 9
Unique values in P_arc: 9

In [17]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor


X = eaf_cleaned[time_input_cols]
y = eaf_cleaned[output_cols]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
train_data = lgb.Dataset(X_train, label=y_train)
test_data = lgb.Dataset(X_test, label=y_test, reference=train_data)
model = MultiOutputRegressor(lgb.LGBMRegressor())
model.fit(X_train, y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000249 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 53
[LightGBM] [Info] Number of data points in the train set: 8664, number of used features: 7
[LightGBM] [Info] Start training from score 0.003941
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000298 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 53
[LightGBM] [Info] Number of data points in the train set: 8664, number of used features: 7
[LightGBM] [Info] Start training from score 0.384745
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000281 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 53
[LightGBM] [Info] Number of data points in the train set: 8664, number of used features: 7
[LightGBM] [Info] Start training from score 0.041839
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000262 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 53
[LightGBM] [Info] Number of data points in the train set: 8664, number of used features: 7
[LightGBM] [Info] Start training from score 1987.132223
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000247 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 53
[LightGBM] [Info] Number of data points in the train set: 8664, number of used features: 7
[LightGBM] [Info] Start training from score 2061.373628

MultiOutputRegressor(estimator=LGBMRegressor())

In [18]:
model.score(X_test, y_test)

0.7762106091232551

In [20]:
import scipy.stats.qmc as qm

sampler = qm.LatinHypercube(d=len(X.columns))

sample = sampler.random(n=100000)
sample_df = pd.DataFrame(
    sample, columns=X.columns
)
sample_df_renomalized = (sample_df * (X.max() - X.min())) + X.min()
predictions = model.predict(sample_df_renomalized)
predictions_df = pd.DataFrame(
    predictions, columns=output_cols
)
predictions_df.describe()

,MX_C_lSc,MX_SiO2_lSl,MX_FeO_lSl,T_lSl,T_lSc
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,0.004760,0.376274,0.053369,2041.160804,2116.833305
std,0.002506,0.028603,0.058643,170.697176,172.409279
min,0.002074,0.247048,0.000069,1414.513857,1492.473934
25%,0.002983,0.356541,0.006318,1939.245446,2013.684224
50%,0.003766,0.382511,0.032128,2054.667871,2131.737425
75%,0.005738,0.397288,0.073014,2151.460424,2227.490942
max,0.021452,0.440931,0.205866,2502.763087,2564.173311

In [21]:
predictions_df.to_csv("../data/eaf/eaf_model_predictions.csv", index=False)